<?php

namespace EricMorand\CategoryLandingPage\Model;

use Magento\Catalog\Model\Category;
use Magento\Store\Model\StoreManagerInterface;
use Magento\UrlRewrite\Service\V1\Data\UrlRewriteFactory;

class LandingPageUrlRewriteGenerator
{
    /**
     * Entity type code
     */
    const ENTITY_TYPE = 'category-landing-page';

    /** @var UrlRewriteFactory */
    protected $_urlRewriteFactory;

    /** @var LandingPageUrlPathGenerator */
    protected $_landingPageUrlPathGenerator;

    /** @var StoreManagerInterface */
    protected $_storeManager;

    public function __construct(
        UrlRewriteFactory $urlRewriteFactory,
        LandingPageUrlPathGenerator $landingPageUrlPathGenerator,
        StoreManagerInterface $storeManager
    )
    {
        $this->_urlRewriteFactory = $urlRewriteFactory;
        $this->_storeManager = $storeManager;
        $this->_landingPageUrlPathGenerator = $landingPageUrlPathGenerator;
    }

    /**
     * @param Category $category
     * @param int|null $storeId
     * @return \Magento\UrlRewrite\Service\V1\Data\UrlRewrite[]
     */
    public function generate($category, int $storeId = null)
    {
        if ($storeId) {
            $urls = $this->generateForStore($category, $storeId);
        } else {
            $urls = $this->generateForAllStores($category);
        }

        return $urls;
    }

    /**
     * @param Category $category
     * @param int $storeId
     * @return \Magento\UrlRewrite\Service\V1\Data\UrlRewrite[]
     */
    protected function generateForStore($category, $storeId)
    {
        return [
            $this->createUrlRewrite($category, $storeId)
        ];
    }

    /**
     * @param Category $category
     * @return \Magento\UrlRewrite\Service\V1\Data\UrlRewrite[]
     */
    protected function generateForAllStores($category)
    {
        $urls = [];

        foreach ($this->_storeManager->getStores() as $store) {
            $urls[] = $this->createUrlRewrite($category, $store->getStoreId());
        }

        return $urls;
    }

    /**
     * @param Category $category
     * @param int $storeId
     * @param int $redirectType
     * @return \Magento\UrlRewrite\Service\V1\Data\UrlRewrite
     */
    protected function createUrlRewrite($category, $storeId, $redirectType = 0)
    {
//        var_dump($storeId); exit;

        return $this->_urlRewriteFactory->create()->setStoreId($storeId)
            ->setEntityType(self::ENTITY_TYPE)
            ->setEntityId($category->getId())
            ->setRequestPath($this->_landingPageUrlPathGenerator->getUrlPath($category))
            ->setTargetPath($this->_landingPageUrlPathGenerator->getCanonicalUrlPath($category))
            ->setIsAutogenerated(1)
            ->setRedirectType($redirectType);
    }
}
